-- tbl_other_material_main
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (1, 'CABLE HENGER YELLOW', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (2, 'CAR GEAT SAFETY SWITCH ONLY FOR MANUAL LIFT', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (3, 'CARGET ANGLE ONLY FOR MANUAL LIFT', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (4, 'CARGET T ONLY FOR MANUAL LIFT', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (5, 'COTTON WEASTE 1 KG', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (6, 'CWT GUIDE CLIP SMALL WITH HARDWARE', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (7, 'DOOR OPEN BELL FOR MANUAL LIFT', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (8, 'DOOR SAFETUY SENSOR  ONLY FOR AUTOMATIC LIFT', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (9, 'EARTH - WIRE SMALL Â 0.5 MM', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (10, 'EARTH - WIRE.BIG 3 KG GALVENISE', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (11, 'EARTHING BRACKET', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (12, 'FINAL LIMIT CAMP 10FT', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (13, 'FLEXIBLE PIPE 3/4"', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (14, 'GEAR OIL 90 NO', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (15, 'GEARED MACHINE UNIT 10 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (16, 'GEARED MACHINE UNIT 13 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (17, 'GEARED MACHINE UNIT 15 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (18, 'GEARED MACHINE UNIT 20 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (19, 'GEARED MACHINE UNIT 25 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (20, 'GEARED MACHINE UNIT 30 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (21, 'GEARED MACHINE UNIT 4 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (22, 'GEARED MACHINE UNIT 5 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (23, 'GEARED MACHINE UNIT 6 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (24, 'GEARED MACHINE UNIT 8 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (25, 'GEARLESS MACHINE UNIT 10 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (26, 'GEARLESS MACHINE UNIT 13 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (27, 'GEARLESS MACHINE UNIT 15 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (28, 'GEARLESS MACHINE UNIT 20 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (29, 'GEARLESS MACHINE UNIT 25 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (30, 'GEARLESS MACHINE UNIT 30 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (31, 'GEARLESS MACHINE UNIT 4 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (32, 'GEARLESS MACHINE UNIT 5 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (33, 'GEARLESS MACHINE UNIT 6 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (34, 'GEARLESS MACHINE UNIT 8 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (35, 'GREACE', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (36, 'HYDRALIC MACHINE FOR 10 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (37, 'HYDRALIC MACHINE FOR 13 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (38, 'HYDRALIC MACHINE FOR 15 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (39, 'HYDRALIC MACHINE FOR 20 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (40, 'HYDRALIC MACHINE FOR 25 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (41, 'HYDRALIC MACHINE FOR 30 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (42, 'HYDRALIC MACHINE FOR 4 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (43, 'HYDRALIC MACHINE FOR 5 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (44, 'HYDRALIC MACHINE FOR 6 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (45, 'HYDRALIC MACHINE FOR 8 PASSENGER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (46, 'JUNCTION BOX & CARTOP JUNCTION AND MAINTENANCE BOX', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (47, 'LANDING LOCK SET WITH HARDWARE ONLY FOR MANUAL LIFT', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (48, 'MACHINE RUBBER', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (49, 'MAGNET SQR SET', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (50, 'OVER LOAD ROPE TYPE 1 st 1', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (51, 'OVER LOAD ROPE TYPE 2 st 1', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (52, 'PENCIL READ', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (53, 'PIT SWITCH BOX', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (54, 'RCR CAMP SET OLYMPUS TYPE ONLY FOR MANUAL LIFT', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (55, 'SADDLE BOX 3/4"', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (56, 'TARMINAL PATA WITH G. CLIP BIG AND HARDWARE', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (57, 'TARMINAL SWITCH O/S TYPE', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (58, 'TRUFFING PLASTIC', true, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tbl_other_material_main (id, material_main_type, active, is_system_defined) VALUES (59, 'WIRE TIE', true, true) ON CONFLICT (id) DO NOTHING;
SELECT setval('tbl_other_material_main_id_seq', 59, true);
