import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import BetaBanner from '@/components/BetaBanner';
import NextTopLoader from 'nextjs-toploader';

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Neerp Client App",
  description: "Generated by AIBI",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <NextTopLoader
          color="#0a76f2"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
          shadow="0 0 10px rgb(10, 242, 169),0 0 5px rgb(34, 102, 197)"
        />
        <BetaBanner />
        <Toaster />
        {children}
      </body>
    </html>
  );
}
