package com.aibi.neerp.quotation.service;

import com.aibi.neerp.employeemanagement.entity.Employee;
import com.aibi.neerp.quotation.dto.QuotationLiftDetailRequestDTO;
import com.aibi.neerp.quotation.dto.QuotationMainRequestDTO;
import com.aibi.neerp.quotation.entity.*;
import com.aibi.neerp.quotation.repository.QuotationMainRepository;
import com.aibi.neerp.quotation.utility.QuotationStatus;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Service // Mark this class as a Spring service component
@RequiredArgsConstructor // Lombok generates constructor for final fields
public class QuotationRevisionService {

    private final QuotationMainRepository quotationMainRepository;

    public QuotationMain reviseQuotationMain(QuotationMain original, Employee revisedBy, QuotationMainRequestDTO dto) {

        // Calculate the new edition as max edition + 1 for this quotation group
        Integer maxEdition = quotationMainRepository.findMaxEditionByQuotationNoAndLeadIdAndCombinedEnquiryId(
                original.getQuotationNo(),
                original.getLead().getLeadId(),
                original.getCombinedEnquiry().getId()
        );
        
        Integer newEdition = (maxEdition != null ? maxEdition : 0) + 1;
        
        System.out.println("🔢 Calculated new edition: " + newEdition + " (max was: " + maxEdition + ")");

        QuotationMain newRevision = QuotationMain.builder()
                // ID is NULL (automatically generated by DB)

                // --- Revision Tracking ---
                .edition(newEdition) // Calculate as max edition + 1
                .parentQuotation(original) // CRITICAL: Links the revision chain
                .isSuperseded(false)       // New revision is active
                .isFinalized(false)        // New revision starts as draft
                .isDeleted(false)

                // --- Header & References (Cloned) ---
                .quotationNo(original.getQuotationNo())
                .quotationDate(LocalDateTime.now()) // Use current date for new revision
                .totalAmount(dto.getTotalQuotationAmount())
                .status(QuotationStatus.DRAFTED) // CRITICAL: Start status as DRAFTED
                .remarks(dto.getRemarks())

                .jobStatus(original.getJobStatus())
                .leadTypeId(original.getLeadTypeId())
                .leadDate(original.getLeadDate())
                .enquiryTypeId(original.getEnquiryTypeId())

                // --- Reference Entities (Cloned as References) ---
                .lead(original.getLead())
                .combinedEnquiry(original.getCombinedEnquiry())
                .customerName(original.getCustomerName())
                .customerId(original.getCustomerId())
                .siteName(original.getSiteName())
                .siteId(original.getSiteId())

                // --- Audit Fields (New/Updated) ---
                .createdBy(original.getCreatedBy()) // Original creator remains
                .createdAt(LocalDateTime.now())     // New creation time stamp
                .revisedBy(revisedBy)
                .revisedAt(LocalDateTime.now())

//                .liftDetails(null)
                .build();

        return newRevision;
    }

//    // ----------------------------------------------------
//    // 2. QuotationLiftDetail Cloning Method
//    // ----------------------------------------------------
//    private QuotationLiftDetail cloneQuotationLiftDetail(QuotationMain newMain, QuotationLiftDetailRequestDTO dto) {
//
//        QuotationLiftDetail newLift = QuotationLiftDetail.builder()
//                // ID is NULL
//                .quotationMain(newMain) // Link to the NEW parent
//
//                // --- Copy all configuration, pricing, dimension fields ---
//                .liftQuotationNo(dto.getLiftQuotationNo())
//                .floors(dto.getFloors())
//                // ... (Copy all other fields from original) ...
//                .liftRate(dto.getLiftRate())
//                .totalAmount(dto.getTotalAmount())
//                .isSaved(false)
//                .isFinalized(false)
//
//                // Copy ManyToMany references (Reference Data copy by value is okay)
//                .floorSelections(dto.getFloorSelectionIds() != null ? new ArrayList<>(dto.getFloorSelectionIds()) : new ArrayList<>())
//                .stdFeatureIds(dto.getStdFeatureIds() != null ? new ArrayList<>(dto.getStdFeatureIds()) : new ArrayList<>())
//                .build();
//
//        // Deep Clone Collections (Materials) - Mapping from DTO
//        if (dto.getManualDetails() != null) {
//            newLift.setManualDetails(dto.getManualDetails().stream()
//                    .map(material -> cloneQuotationLiftMaterial(material, newLift, "MANUAL"))
//                    .collect(Collectors.toList()));
//        }
//
//        // Repeat for other material lists (commonDetails, otherDetails)
//
//        if (dto.getSelectedMaterials() != null) {
//            newLift.setSelectedMaterials(dto.getSelectedMaterials().stream()
//                    .map(selected -> cloneSelectedQuotationMaterial(selected, newLift))
//                    .collect(Collectors.toList()));
//        }
//        return newLift;
//    }
//
//    // ----------------------------------------------------
//    // 3. Nested Material Cloning Methods
//    // ----------------------------------------------------
//    private QuotationLiftMaterial cloneQuotationLiftMaterial(QuotationLiftMaterial original, QuotationLiftDetail newLift) {
//        return QuotationLiftMaterial.builder()
//                // ID is NULL
//                .liftDetail(newLift)
//                // ... (copy all fields) ...
//                .listType(original.getListType())
//                .otherMaterialName(original.getOtherMaterialName())
//                .quantity(original.getQuantity())
//                .price(original.getPrice())
//                .build();
//    }
//
//    private SelectedQuotationMaterial cloneSelectedQuotationMaterial(SelectedQuotationMaterial original, QuotationLiftDetail newLift) {
//        return SelectedQuotationMaterial.builder()
//                // ID is NULL
//                .quotationLiftDetail(newLift)
//                // ... (copy all fields) ...
//                .materialName(original.getMaterialName())
//                .quantity(original.getQuantity())
//                .unitPrice(original.getUnitPrice())
//                .price(original.getPrice())
//                .createdAt(LocalDateTime.now()) // New timestamp
//                .build();
//    }


}