package com.aibi.neerp.amc.quatation.pdf.service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;

@Service
@Slf4j
public class EmailService {

    @Autowired
    private JavaMailSender mailSender;

    @Value("${resend.from.email}")
    private String fromEmail;

    public void sendEmailWithAttachment(MultipartFile file) throws MessagingException, IOException {
        
        // HARDCODED VALUES (To be replaced by DB logic later)
        String toEmail = "ss8883484@gmail.com"; // Put your test email here
        String subject = "System Generated Report - NEERP";
        String body = "Hello,\n\nPlease find the attached PDF document generated by the NEERP system.\n\nRegards,\nAdmin";

        log.info("Sending hardcoded email to: {}", toEmail);

        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");

            helper.setFrom(fromEmail);
            helper.setTo(toEmail);
            helper.setSubject(subject);
            helper.setText(body);

            if (file != null && !file.isEmpty()) {
                String fileName = file.getOriginalFilename() != null ? file.getOriginalFilename() : "document.pdf";
                log.debug("Attaching file: {}", fileName);
                helper.addAttachment(fileName, file);
            }

            mailSender.send(message);
            log.info("Hardcoded email sent successfully to {}", toEmail);

        } catch (Exception e) {
            log.error("Failed to send hardcoded email: {}", e.getMessage());
            throw e;
        }
    }
}
